const $=id=>document.getElementById(id),fmt=n=>n.toLocaleString('ko-KR'),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records=new Map(),mode='orders',busy=false;
const activeHours=()=>$('timeScope').value==='all'?OKPOS.allHours:OKPOS.hours;
const count=rs=>rs.reduce((n,r)=>n+(r.count??1),0);
const summarize=rs=>OKPOS.summarize(rs,activeHours());
const chosen=()=>[...records.values()].filter(r=>(!$('store').value||r.store===$('store').value)&&(!$('from').value||r.day>=$('from').value)&&(!$('to').value||r.day<=$('to').value));
function setOptions(){const before=$('store').value,stores=[...new Set([...records.values()].map(r=>r.store))];$('store').innerHTML='<option value="">전체 매장</option>'+stores.map(s=>`<option>${esc(s)}</option>`).join('');$('store').value=stores.includes(before)?before:'';const dates=[...records.values()].map(r=>r.day).sort();$('from').value=dates[0]||'';$('to').value=dates.at(-1)||'';}
function render(){$('scopeLabel').textContent=$('timeScope').value==='all'?'전체 24시간 · 00 = 24시':'15:00 → 다음 날 04:59 · 00 = 24시';$('chart').style.gridTemplateColumns=`repeat(${activeHours().length},minmax(30px,1fr))`;const rs=chosen(),s=summarize(rs),sum=k=>s.reduce((a,b)=>a+b[k],0),days=[...new Set(rs.map(r=>r.day))].sort();$('orders').textContent=rs.length?fmt(sum('orders'))+' 건':'—';$('payments').textContent=rs.length?fmt(sum('payments'))+' 건':'—';$('amount').textContent=rs.length?fmt(sum('amount'))+' 원':'—';const max=Math.max(...s.map(x=>x.orders));const peaks=s.filter(x=>x.orders===max);$('peak').textContent=max?peaks.map(x=>OKPOS.label(x.hour)).join(' · '):'—';$('peakNote').textContent=max?`시간당 ${max}건${peaks.length>1?' · 공동 피크':''}`:'가장 많은 주문이 들어온 시간';$('period').textContent=days.length?`${days[0]}${days.length>1?' — '+days.at(-1):''} · ${days.length}영업일`:'조회할 데이터가 없습니다';
 const top=Math.max(1,...s.map(x=>Math.abs(x[mode])));$('chart').innerHTML=s.map(x=>`<div class="barcol" title="${OKPOS.label(x.hour)}: ${fmt(x[mode])}${mode==='amount'?'원':'건'}"><span class="barvalue">${mode==='amount'&&Math.abs(x.amount)>=10000?(x.amount/10000).toFixed(1)+'만':fmt(x[mode])}</span><div class="bar ${x.hour<5?'night':''} ${x[mode]===top?'hot':''}" style="height:${Math.max(1,Math.abs(x[mode])/top*185)}px;${x[mode]<0?'background:#c17260':''}"></div><span class="barlabel">${OKPOS.label(x.hour)}</span></div>`).join('');
 const row=(label,a,cls='')=>`<tr class="${cls}"><td>${esc(label)}</td>${a.map(x=>`<td>${x.orders} / ${x.payments}<small>${fmt(x.amount)}</small></td>`).join('')}<td>${a.reduce((n,x)=>n+x.orders,0)} / ${a.reduce((n,x)=>n+x.payments,0)}<small>${fmt(a.reduce((n,x)=>n+x.amount,0))}</small></td></tr>`;
 $('matrix').innerHTML='<thead><tr><th>영업일자</th>'+activeHours().map(h=>`<th>${OKPOS.label(h)}</th>`).join('')+'<th>합계</th></tr></thead><tbody>'+(days.length?days.map(d=>row(d,summarize(rs.filter(r=>r.day===d)))).join('')+row('전체 합계',s,'total'):`<tr><td colspan="${activeHours().length+2}" class="empty">엑셀 파일을 추가해주세요.</td></tr>`)+'</tbody>';
 $('recordCount').textContent=`홀 영수증 ${rs.filter(r=>r.system!=='MATE').length}개 · 메이트 시간대 자료 ${rs.filter(r=>r.system==='MATE').length}행`;
 $('receipts').innerHTML='<thead><tr>'+['영업일','매장','출처','포스','영수증/자료','구분','주문 시간','결제 집계 시간','건수','실매출액'].map(x=>`<th>${x}</th>`).join('')+'</tr></thead><tbody>'+rs.map(r=>'<tr>'+[r.day,r.store,r.system==='MATE'?'MATE '+r.channel:'OKPOS',r.pos,r.receipt,r.type,r.order===null?'미확인':OKPOS.label(r.order),r.pay===null?'미확인':OKPOS.label(r.pay)+(r.system==='MATE'?' (주문 기준)':''),r.count??1,fmt(r.amount)+'원'].map(x=>`<td>${esc(x)}</td>`).join('')+'</tr>').join('')+'</tbody>';
 $('breakdown').innerHTML='<thead><tr><th>구분</th><th>주문 건수</th><th>결제 집계 건수</th><th>매출</th></tr></thead><tbody>'+[['OKPOS 홀',r=>r.system!=='MATE'],['MATE 배달',r=>r.channel==='배달'],['MATE 포장',r=>r.channel==='포장']].map(([name,predicate])=>{const a=summarize(rs.filter(predicate));return `<tr><td>${name}</td><td>${fmt(a.reduce((n,x)=>n+x.orders,0))}</td><td>${fmt(a.reduce((n,x)=>n+x.payments,0))}</td><td>${fmt(a.reduce((n,x)=>n+x.amount,0))}원</td></tr>`}).join('')+'</tbody>';
 const outside=rs.filter(r=>r.type==='매출'&&!activeHours().includes(r.pay)),orderOutside=rs.filter(r=>r.type==='매출'&&!activeHours().includes(r.order)),amountOutside=rs.filter(r=>!activeHours().includes(r.order)),returns=rs.filter(r=>r.type!=='매출');$('warnings').textContent=[outside.length?`결제시간 범위 밖 또는 미확인: ${count(outside)}건 (결제 건수 집계 제외)`:'',orderOutside.length?`최초주문 시간 범위 밖 또는 미확인: ${count(orderOutside)}건 (주문 집계 제외)`:'',amountOutside.length?`최초주문 시간 범위 밖 또는 미확인 매출: ${count(amountOutside)}건 · ${fmt(amountOutside.reduce((n,r)=>n+r.amount,0))}원 (현재 시간 범위에서 제외 · 전체 24시간 조회 가능)`:'',returns.length?`매출 외 구분 ${returns.length}건: 테이블·결제 건수에서 제외, 실매출액은 최초주문 시간에 원본 금액으로 반영`:'' ].filter(Boolean).join('\n');$('export').disabled=!rs.length;$('exportExcel').disabled=!rs.length;
}
async function upload(files){if(busy)return;busy=true;$('status').textContent='엑셀을 분석하고 있어요…';let added=0,duplicate=0,conflict=0,errors=[];const cache=new Map(),incomingStores=new Set();for(const f of files){try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:false});cache.set(f,wb);for(const name of wb.SheetNames){const a=OKPOS.parse(XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true}),f.name,name);if(a)a.forEach(r=>incomingStores.add(r.store));}}catch{}}
 const existingStores=new Set([...records.values()].filter(r=>r.system!=='MATE').map(r=>r.store));let mateStore=$('deliveryStore').value.trim();if(incomingStores.size===1)mateStore=[...incomingStores][0];else if(incomingStores.size===0&&existingStores.size===1)mateStore=[...existingStores][0];else if(incomingStores.size>1)mateStore='';$('deliveryStore').value=mateStore;
 for(const f of files){try{if(!/\.(xlsx|xls)$/i.test(f.name))throw Error('엑셀 파일만 선택해주세요.');const wb=cache.get(f)||XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:false});let found=false,staged=[];for(const name of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true});const a=OKPOS.parse(rows,f.name,name)??OKPOS.parseMate(rows,f.name,name,mateStore);if(a){found=true;staged.push(...a)}}if(!found||!staged.length)throw Error('OKPOS 영수증 또는 MATE 시간대별 데이터를 찾지 못했습니다.');const local=new Map();for(const r of staged){if(local.has(r.key))throw Error('같은 영수증이 파일 내에서 반복됩니다. 원본을 확인해주세요.');local.set(r.key,r)}for(const r of staged){const old=records.get(r.key);if(old){if(old.amount===r.amount&&old.order===r.order&&old.pay===r.pay&&old.lines===r.lines&&(old.count??1)===(r.count??1))duplicate++;else conflict++;}else{records.set(r.key,r);added++}}}catch(e){errors.push(f.name+': '+e.message)}}setOptions();render();$('status').textContent=`${added}행 추가${mateStore?' · 메이트 연결 매장: '+mateStore:''}${duplicate?' · 중복 '+duplicate+'개 제외':''}${conflict?' · 기존 자료와 다른 '+conflict+'개는 반영하지 않았습니다. 데이터를 비우고 최신 파일을 다시 올려주세요.':''}${errors.length?'\n'+errors.join('\n'):''}\n현재 화면에서만 분석됩니다. 새로고침하면 모든 업로드 데이터가 초기화됩니다.`;busy=false;$('files').value='';}
$('files').onchange=e=>upload(e.target.files);$('choose').onclick=$('uploadTop').onclick=()=>$('files').click();['dragenter','dragover'].forEach(t=>$('drop').addEventListener(t,e=>{e.preventDefault();$('drop').classList.add('drag')}));['dragleave','drop'].forEach(t=>$('drop').addEventListener(t,e=>{e.preventDefault();$('drop').classList.remove('drag')}));$('drop').addEventListener('drop',e=>upload(e.dataTransfer.files));['store','from','to','timeScope'].forEach(id=>$(id).onchange=render);$('all').onclick=()=>{setOptions();render()};$('clear').onclick=()=>{if(records.size&&confirm('현재 불러온 데이터를 모두 비울까요?')){records.clear();$('deliveryStore').value='';setOptions();render();$('status').textContent='데이터를 비웠습니다. 새 엑셀 파일을 추가해주세요.'}};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));render()});
$('export').onclick=()=>{const rs=chosen(),days=[...new Set(rs.map(r=>r.day))].sort(),rows=[['영업일자','시간대','주문건수_홀배달포장','결제건수','최초주문기준실매출액']];for(const d of days)for(const x of summarize(rs.filter(r=>r.day===d)))rows.push([d,OKPOS.label(x.hour),x.orders,x.payments,x.amount]);const blob=new Blob(['\ufeff'+rows.map(r=>r.join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='시간대별_집계.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_hourly_summary',description:'현재 선택된 매장 및 영업일의 시간대별 주문·결제 집계를 조회합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input&&Object.keys(input).length)throw Error('입력값이 필요하지 않습니다.');return {start:$('from').value,end:$('to').value,store:$('store').value,hours:summarize(chosen())}}})).catch(()=>{})}catch{}}
setOptions();render();

$('exportExcel').onclick=()=>{try{const rs=chosen();const wb=OKPOSExcel.build(rs,{store:$('store').value,from:$('from').value,to:$('to').value,hours:activeHours()});XLSX.writeFile(wb,`시간대별_분석_${$('from').value||'전체'}_${$('to').value||'전체'}.xlsx`,{compression:true});$('status').textContent='엑셀 다운로드를 시작했습니다. 최초주문 건수 / 결제 건수 / 최초주문 기준 매출 시트로 나누어 저장됩니다.';}catch(e){$('status').textContent='엑셀 다운로드 실패: '+e.message;}};
